[Application]
FileLogger\Age=1
FileLogger\AgeType=1
FileLogger\Backup=true
FileLogger\DeleteOld=true
FileLogger\Enabled=true
FileLogger\MaxSizeBytes=66560
FileLogger\Path=/config/qBittorrent/logs

[AutoRun]
enabled=false
program=

[BitTorrent]
ExcludedFileNamesEnabled=true
Session\AlternativeGlobalDLSpeedLimit=0
Session\AlternativeGlobalUPSpeedLimit=150
Session\ConnectionSpeed=5
Session\DefaultSavePath=/data/downloads/torrents
Session\ExcludedFileNames=*.lnk, *.zipx, *sample.mkv, *sample.avi, *sample.mp4, *.py, *.vbs, *.html, *.php, *.torrent, *.exe, *.bat, *.cmd, *.com, *.cpl, *.dll, *.js, *.jse, *.msi, *.msp, *.pif, *.scr, *.vbs, *.vbe, *.wsf, *.wsh, *.hta, *.reg, *.inf, *.ps1, *.ps2, *.psm1, *.psd1, *.sh, *.apk, *.app, *.ipa, *.iso, *.jar, *.bin, *.tmp, *.vb, *.vxd, *.ocx, *.drv, *.sys, *.scf, *.ade, *.adp, *.bas, *.chm, *.crt, *.hlp, *.ins, *.isp, *.key, *.mda, *.mdb, *.mdt, *.mdw, *.mdz, *.potm, *.potx, *.ppam, *.ppsx, *.pptm, *.sldm, *.sldx, *.xlam, *.xlsb, *.xlsm, *.xltm, *.nsh, *.mht, *.mhtml
Session\GlobalDLSpeedLimit=0
Session\GlobalMaxRatio=0
Session\GlobalUPSpeedLimit=150
Session\IgnoreLimitsOnLAN=true
Session\MaxActiveDownloads=5
Session\MaxActiveUploads=5
Session\MaxConnections=40
Session\MaxConnectionsPerTorrent=-1
Session\MaxUploads=-1
Session\MaxUploadsPerTorrent=-1
Session\Port=24113
Session\QueueingSystemEnabled=true
Session\TempPath=/downloads/incomplete/
Session\UseAlternativeGlobalSpeedLimit=false
Session\uTPRateLimited=false

[Core]
AutoDeleteAddedTorrentFile=Never

[LegalNotice]
Accepted=true

[Meta]
MigrationVersion=6

[Network]
Cookies=@Invalid()
PortForwardingEnabled=true
Proxy\HostnameLookupEnabled=false
Proxy\Profiles\BitTorrent=true
Proxy\Profiles\Misc=true
Proxy\Profiles\RSS=true

[Preferences]
Connection\PortRangeMin=6881
Connection\UPnP=false
Downloads\SavePath=/downloads/
Downloads\TempPath=/downloads/incomplete/
General\Locale=en
MailNotification\req_auth=true
WebUI\Address=*
WebUI\Password_PBKDF2="@ByteArray(zJRsNjJSdhr3Vxeng6K5Zg==:H8bmi+65To4xBbaQdecW8F/J6Zsf01oxFY2sCS+PPgdmW6k0Bs1jx1MfZR3NgVzv9XIPp2yaatM3eAgLNSresg==)"
WebUI\Port=8081
WebUI\ServerDomains=*
WebUI\Username=adminn

[RSS]
AutoDownloader\DownloadRepacks=true
AutoDownloader\SmartEpisodeFilter=s(\\d+)e(\\d+), (\\d+)x(\\d+), "(\\d{4}[.\\-]\\d{1,2}[.\\-]\\d{1,2})", "(\\d{1,2}[.\\-]\\d{1,2}[.\\-]\\d{4})"
